#!/bin/bash
# Start Gnome 3 Desktop 
#unset SESSION_MANAGER
#unset DBUS_SESSION_BUS_ADDRESS

#[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
#vncconfig -iconic &
#/usr/bin/gnome-terminal &
#/usr/bin/xterm &
#!/bin/bash
#xrdb $HOME/.Xresources
#startxfce4 &

dbus-launch --exit-with-session gnome-session
